In [ ]:
import tensorflow as tf
x_data=[[73.,80.,75.],[93.,88.,93.],[89.,91.,90.],[96.,98.,100.],[73.,66.,70.]]
y_data=[[152.],[185.],[180.],[196.],[142.]]

X=tf.placeholder(tf.float32, shape=[None,3])
Y=tf.placeholder(tf.float32, shape=[None,1])

W=tf.Variable(tf.random_normal([3,1]), name='weight')
b=tf.Variable(tf.random_normal([1]), name='bias')

hypothesis=tf.matmul(X,W)+b
cost=tf.reduce_mean(tf.square(hypothesis-Y))

optimizer=tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train=optimizer.minimize(cost)

sess=tf.Session()

sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _=sess.run([cost,hypothesis,train],feed_dict={X:x_data, Y:y_data})
    if step % 10 ==0:
        print(step,"W is ",sess.run(W),"Cost: ",cost_val, "\nPrediction\n",hy_val)


0 W is  [[-0.12582251]
 [ 1.9508734 ]
 [-0.00879337]] Cost:  1087.8864 
Prediction
 [[132.98409]
 [143.37016]
 [149.97726]
 [161.33818]
 [106.75831]]
10 W is  [[-0.05289963]
 [ 2.016591  ]
 [ 0.06258606]] Cost:  48.870693 
Prediction
 [[161.46791]
 [177.6569 ]
 [183.7339 ]
 [198.10135]
 [132.92072]]
20 W is  [[-0.04953817]
 [ 2.012836  ]
 [ 0.06360161]] Cost:  48.598045 
Prediction
 [[161.52702]
 [177.77919]
 [183.82774]
 [198.2066 ]
 [133.02419]]
30 W is  [[-0.04639565]
 [ 2.0088813 ]
 [ 0.06440216]] Cost:  48.336388 
Prediction
 [[161.50026]
 [177.79808]
 [183.81978]
 [198.20099]
 [133.04878]]
40 W is  [[-0.04326225]
 [ 2.0049367 ]
 [ 0.06519996]] Cost:  48.076122 
Prediction
 [[161.47327]
 [177.81656]
 [183.8115 ]
 [198.19499]
 [133.07304]]
50 W is  [[-0.04013744]
 [ 2.0010028 ]
 [ 0.06599551]] Cost:  47.817406 
Prediction
 [[161.44637]
 [177.835  ]
 [183.80327]
 [198.18904]
 [133.09723]]
60 W is  [[-0.03702109]
 [ 1.9970796 ]
 [ 0.06678891]] Cost:  47.559868 
Prediction
 [[161.4195